<a href="https://colab.research.google.com/github/rafijonathan/datamaining/blob/main/Pengangguran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   Nama  :Rafi jonathan S
*   Mapel :Penambangan Data
*   Nim   :A11.2022.14760

Dataset berasal dari : https://www.kaggle.com/datasets/panjikumbara/dataset-pengangguran-indonesia-tingkat-pendidikan

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks')

Mounted at /content/drive

import library yang digunakan

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
import pandas as pd

dataset =pd.read_csv('/content/drive/My Drive/Colab Notebooks/Dataset Pengangguran Indonesia Tingkat Pendidikan.csv', sep=',')
x =dataset.iloc[:, :-1].values
y =dataset.iloc[:, -1].values

In [ ]:
print (x)

[[2006 'Februari' 234465 614960 2675459 2860007 2842876 1204140 297185
  375601]
 [2006 'Agustus' 170666 611254 2589699 2730045 2851518 1305190 278074
  395554]
 [2007 'Februari' 145750 520316 2753548 2643062 2630360 1114675 330316
  409890]
 [2007 'Agustus' 94301 438519 2179792 2264198 2532204 1538349 397191
  566588]
 [2008 'Februari' 79764 448431 2216748 2166619 2204377 1165582 519867
  626202]
 [2008 'Agustus' 103206 443832 2099968 1973986 2403394 1409128 362683
  598318]
 [2009 'Februari' 60347 415955 2143747 2054682 2133627 1337586 486399
  626621]
 [2009 'Agustus' 90471 547430 1531671 1770823 2472245 1407226 441100
  701651]
 [2010 'Februari' 59066 547164 1522465 1657452 2111256 1336881 538186
  820020]
 [2010 'Agustus' 157586 600221 1402858 1661449 2149123 1195192 443222
  710128]
 [2011 'Februari' 93956 559661 1291733 1834632 2385938 1109511 469009
  635442]
 [2011 'Agustus' 205388 737610 1241882 2138864 2376254 1161362 276816
  543216]
 [2012 'Februari' 126972 601753 1418683 1736670 2043697 1018465 258385
  553206]
 [2012 'Agustus' 85374 512041 1452047 1714776 1867755 1067009 200028
  445836]
 [2013 'Februari' 112435 523400 1421873 1821429 1874799 864649 197270
  425042]
 [2013 'Agustus' 81432 489152 1347555 1689643 1925660 1258201 185103
  434185]
 [2014 'Februari' 134040 610574 1374822 1693203 1893509 847365 195258
  398298]
 [2014 'Agustus' 74898 389550 1229652 1566838 1962786 1332521 193517
  495143]
 [2015 'Februari' 124303 603194 1320392 1650387 1762411 1174366 254312
  565402]
 [2015 'Agustus' 55554 371542 1004961 1373919 2280029 1569690 251541
  653586]
 [2016 'Februari' 94293 557418 1218954 1313815 1546699 1348327 249362
  695304]
 [2016 'Agustus' 59346 384069 1035731 1294483 1950626 1520549 219736
  567235]
 [2017 'Februari' 92331 546897 1292234 1281240 1552894 1383022 249705
  606939]
 [2017 'Agustus' 62984 404435 904561 1274417 1910829 1621402 242937
  618758]
 [2018 'Februari' 43740 452326 975661 1265421 1672601 1445340 304744
  803624]
 [2018 'Agustus' 32315 328781 908228 1142168 1945826 1752241 223456
  740370]
 [2019 'Februari' 36422 443495 965641 1235199 1690527 1397281 274377
  855854]
 [2019 'Agustus' 40771 347712 865778 1137195 2008035 1739625 218954
  746354]
 [2020 'Februari' 35761 346778 1006744 1251352 1748834 1443522 267583
  824912]
 [2020 'Agustus' 31379 428813 1410537 1621518 2662444 2326599 305261
  981203]
 [2021 'Februari' 20461 342734 1219494 1515089 2305093 2089137 254457
  999543]
 [2021 'Agustus' 23905 431329 1393492 1604448 2472859 2111338 216024
  848657]
 [2022 'Februari' 24852 437819 1230914 1460221 2251558 1876661 235359
  884769]
 [2022 'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490
  673485]
 [2022 'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490
  673485]]

In [ ]:
print(y)

[11104693 10932000 10547917 10011142  9427590  9394515  9258964  8962617
  8592490  8319779  8379882  8681392  7757831  7344866  7240897  7410931
  7147069  7244905  7454767  7560822  7024172  7031775  7005262  7005262
  6963457  7073385  6898796  7104424  6925486  9767754  8746008  9102052
  8402153  8425931  8425931]

Menghilangkan Missing Value(nan)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[[2006 'Februari' 234465 614960 2675459 2860007 2842876 1204140 297185
  375601]
 [2006 'Agustus' 170666 611254 2589699 2730045 2851518 1305190 278074
  395554]
 [2007 'Februari' 145750 520316 2753548 2643062 2630360 1114675 330316
  409890]
 [2007 'Agustus' 94301 438519 2179792 2264198 2532204 1538349 397191
  566588]
 [2008 'Februari' 79764 448431 2216748 2166619 2204377 1165582 519867
  626202]
 [2008 'Agustus' 103206 443832 2099968 1973986 2403394 1409128 362683
  598318]
 [2009 'Februari' 60347 415955 2143747 2054682 2133627 1337586 486399
  626621]
 [2009 'Agustus' 90471 547430 1531671 1770823 2472245 1407226 441100
  701651]
 [2010 'Februari' 59066 547164 1522465 1657452 2111256 1336881 538186
  820020]
 [2010 'Agustus' 157586 600221 1402858 1661449 2149123 1195192 443222
  710128]
 [2011 'Februari' 93956 559661 1291733 1834632 2385938 1109511 469009
  635442]
 [2011 'Agustus' 205388 737610 1241882 2138864 2376254 1161362 276816
  543216]
 [2012 'Februari' 126972 601753 1418683 1736670 2043697 1018465 258385
  553206]
 [2012 'Agustus' 85374 512041 1452047 1714776 1867755 1067009 200028
  445836]
 [2013 'Februari' 112435 523400 1421873 1821429 1874799 864649 197270
  425042]
 [2013 'Agustus' 81432 489152 1347555 1689643 1925660 1258201 185103
  434185]
 [2014 'Februari' 134040 610574 1374822 1693203 1893509 847365 195258
  398298]
 [2014 'Agustus' 74898 389550 1229652 1566838 1962786 1332521 193517
  495143]
 [2015 'Februari' 124303 603194 1320392 1650387 1762411 1174366 254312
  565402]
 [2015 'Agustus' 55554 371542 1004961 1373919 2280029 1569690 251541
  653586]
 [2016 'Februari' 94293 557418 1218954 1313815 1546699 1348327 249362
  695304]
 [2016 'Agustus' 59346 384069 1035731 1294483 1950626 1520549 219736
  567235]
 [2017 'Februari' 92331 546897 1292234 1281240 1552894 1383022 249705
  606939]
 [2017 'Agustus' 62984 404435 904561 1274417 1910829 1621402 242937
  618758]
 [2018 'Februari' 43740 452326 975661 1265421 1672601 1445340 304744
  803624]
 [2018 'Agustus' 32315 328781 908228 1142168 1945826 1752241 223456
  740370]
 [2019 'Februari' 36422 443495 965641 1235199 1690527 1397281 274377
  855854]
 [2019 'Agustus' 40771 347712 865778 1137195 2008035 1739625 218954
  746354]
 [2020 'Februari' 35761 346778 1006744 1251352 1748834 1443522 267583
  824912]
 [2020 'Agustus' 31379 428813 1410537 1621518 2662444 2326599 305261
  981203]
 [2021 'Februari' 20461 342734 1219494 1515089 2305093 2089137 254457
  999543]
 [2021 'Agustus' 23905 431329 1393492 1604448 2472859 2111338 216024
  848657]
 [2022 'Februari' 24852 437819 1230914 1460221 2251558 1876661 235359
  884769]
 [2022 'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490
  673485]
 [2022 'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490
  673485]]

Encoding data kategori(Atribute)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 234465 614960 2675459 2860007 2842876 1204140 297185 375601]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 170666 611254 2589699 2730045 2851518 1305190 278074 395554]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 145750 520316 2753548 2643062 2630360 1114675 330316 409890]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 94301 438519 2179792 2264198 2532204 1538349 397191 566588]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 79764 448431 2216748 2166619 2204377 1165582 519867 626202]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 103206 443832 2099968 1973986 2403394 1409128 362683 598318]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 60347 415955 2143747 2054682 2133627 1337586 486399 626621]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 90471 547430 1531671 1770823 2472245 1407226 441100 701651]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 59066 547164 1522465 1657452 2111256 1336881 538186 820020]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 157586 600221 1402858 1661449 2149123 1195192 443222 710128]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 93956 559661 1291733 1834632 2385938 1109511 469009 635442]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 205388 737610 1241882 2138864 2376254 1161362 276816 543216]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 126972 601753 1418683 1736670 2043697 1018465 258385 553206]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 85374 512041 1452047 1714776 1867755 1067009 200028 445836]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 112435 523400 1421873 1821429 1874799 864649 197270 425042]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 81432 489152 1347555 1689643 1925660 1258201 185103 434185]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 134040 610574 1374822 1693203 1893509 847365 195258 398298]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 74898 389550 1229652 1566838 1962786 1332521 193517 495143]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 124303 603194 1320392 1650387 1762411 1174366 254312 565402]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 55554 371542 1004961 1373919 2280029 1569690 251541 653586]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 94293 557418 1218954 1313815 1546699 1348327 249362 695304]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 59346 384069 1035731 1294483 1950626 1520549 219736 567235]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 92331 546897 1292234 1281240 1552894 1383022 249705 606939]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 62984 404435 904561 1274417 1910829 1621402 242937 618758]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  'Februari' 43740 452326 975661 1265421 1672601 1445340 304744 803624]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  'Agustus' 32315 328781 908228 1142168 1945826 1752241 223456 740370]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  'Februari' 36422 443495 965641 1235199 1690527 1397281 274377 855854]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  'Agustus' 40771 347712 865778 1137195 2008035 1739625 218954 746354]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Februari' 35761 346778 1006744 1251352 1748834 1443522 267583 824912]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Agustus' 31379 428813 1410537 1621518 2662444 2326599 305261 981203]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  'Februari' 20461 342734 1219494 1515089 2305093 2089137 254457 999543]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  'Agustus' 23905 431329 1393492 1604448 2472859 2111338 216024 848657]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Februari' 24852 437819 1230914 1460221 2251558 1876661 235359 884769]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490 673485]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490 673485]]

Encoding data kategori(class/label)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[32 31 30 29 27 26 25 23 20 16 17 21 15 11  9 12  8 10 13 14  4  5  3  3
  2  6  0  7  1 28 22 24 18 19 19]

Membagi dataset ke dalam training set dan test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  'Agustus' 40771 347712 865778 1137195 2008035 1739625 218954 746354]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  'Februari' 36422 443495 965641 1235199 1690527 1397281 274377 855854]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Februari' 24852 437819 1230914 1460221 2251558 1876661 235359 884769]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 74898 389550 1229652 1566838 1962786 1332521 193517 495143]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  'Februari' 43740 452326 975661 1265421 1672601 1445340 304744 803624]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 79764 448431 2216748 2166619 2204377 1165582 519867 626202]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 145750 520316 2753548 2643062 2630360 1114675 330316 409890]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 62984 404435 904561 1274417 1910829 1621402 242937 618758]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  'Agustus' 32315 328781 908228 1142168 1945826 1752241 223456 740370]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 93956 559661 1291733 1834632 2385938 1109511 469009 635442]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  'Agustus' 23905 431329 1393492 1604448 2472859 2111338 216024 848657]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 59346 384069 1035731 1294483 1950626 1520549 219736 567235]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  'Februari' 20461 342734 1219494 1515089 2305093 2089137 254457 999543]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 94293 557418 1218954 1313815 1546699 1348327 249362 695304]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 124303 603194 1320392 1650387 1762411 1174366 254312 565402]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 60347 415955 2143747 2054682 2133627 1337586 486399 626621]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 85374 512041 1452047 1714776 1867755 1067009 200028 445836]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 90471 547430 1531671 1770823 2472245 1407226 441100 701651]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490 673485]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 170666 611254 2589699 2730045 2851518 1305190 278074 395554]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 134040 610574 1374822 1693203 1893509 847365 195258 398298]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 234465 614960 2675459 2860007 2842876 1204140 297185 375601]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 81432 489152 1347555 1689643 1925660 1258201 185103 434185]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 103206 443832 2099968 1973986 2403394 1409128 362683 598318]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 205388 737610 1241882 2138864 2376254 1161362 276816 543216]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 157586 600221 1402858 1661449 2149123 1195192 443222 710128]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 59066 547164 1522465 1657452 2111256 1336881 538186 820020]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 126972 601753 1418683 1736670 2043697 1018465 258385 553206]]

In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 112435 523400 1421873 1821429 1874799 864649 197270 425042]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 55554 371542 1004961 1373919 2280029 1569690 251541 653586]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 94301 438519 2179792 2264198 2532204 1538349 397191 566588]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Agustus' 31379 428813 1410537 1621518 2662444 2326599 305261 981203]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Agustus' 15206 663125 1274153 1500807 2478173 1661492 159490 673485]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Februari' 35761 346778 1006744 1251352 1748834 1443522 267583 824912]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 92331 546897 1292234 1281240 1552894 1383022 249705 606939]]

In [ ]:
print(y_train)

[ 7  0 18 10  2 27 30  3  6 17 24  5 22  4 13 25 11 23 19 31  8 32 12 26
 21 16 20 15]

In [ ]:
print(y_test)

[ 9 14 29 28 19  1  3]

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, -2:] = sc.fit_transform(x_train[:, -2:])
x_test[:, -2:] = sc.transform(x_test[:, -2:])

In [ ]:
print(x_train)

[[0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 'Agustus'
  40771 347712 865778 1137195 2008035 1.1380838847986283
  -0.7316287437470185 0.6854337894505074]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  'Februari' 36422 443495 965641 1235199 1690527 0.013616478721528049
  -0.21499653388438913 1.3570140993575126]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Februari' 24852 437819 1230914 1460221 2251558 1.588194053106475
  -0.5787075485248826 1.5343542332475677]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  74898 389550 1229652 1566838 1962786 -0.1990950313898015
  -0.9687428213371111 -0.8552818382394346]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  'Februari' 43740 452326 975661 1265421 1672601 0.17147167428113874
  0.06807313605225203 1.036679491262144]
 [0 0 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 79764 448431 2216748 2166619 2204377 -0.7474249694144347
  2.0733682460657556 -0.051476871699688655]
 [0 1 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 145750 520316 2753548 2643062 2630360 -0.9146347415768413
  0.30644563249970447 -1.3781515748650226]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  62984 404435 904561 1274417 1910829 0.7497671327928883
  -0.5080683033317498 -0.09713206646633474]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 'Agustus'
  32315 328781 908228 1142168 1945826 1.1795225569969687
  -0.6896628052593589 0.6487329988159547]
 [0 0 0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 93956 559661 1291733 1834632 2385938 -0.9315964808945515
  1.5992892368242204 0.005193466780135332]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 'Agustus'
  23905 431329 1393492 1604448 2472859 2.3590170774794905
  -0.75894109376231 1.3128737935091042]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  59346 384069 1035731 1294483 1950626 0.4185041011490045
  -0.724339235995497 -0.41313053502650476]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  'Februari' 20461 342734 1219494 1515089 2305093 2.286095393786136
  -0.4006832275037092 2.2382807947933814]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 94293 557418 1218954 1313815 1546699 -0.1471784450893124
  -0.44817688734258654 0.37233630250299504]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 124303 603194 1320392 1650387 1762411 -0.7185729325889573
  -0.40203486257272536 -0.4243726054197426]
 [0 0 0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 60347 415955 2143747 2054682 2133627 -0.18245846871664087
  1.7613922288945003 -0.04890708037684815]
 [0 0 0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  85374 512041 1452047 1714776 1867755 -1.071199084395968
  -0.9080497459277038 -1.157689238610071]
 [0 0 0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  90471 547430 1531671 1770823 2472245 0.04628195074217618
  1.3391321117126942 0.4112634278635408]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 'Agustus'
  15206 663125 1274153 1500807 2478173 0.8814472507725548
  -1.2859296247399525 0.2385170259563197]
 [1 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  170666 611254 2589699 2730045 2851518 -0.2888667775734449
  -0.1805345004350605 -1.4660764636579617]
 [0 0 0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 134040 610574 1374822 1693203 1893509 -1.792644527986037
  -0.9525138788877519 -1.4492470904124382]
 [1 0 0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 234465 614960 2675459 2860007 2842876 -0.6207768778938565
  -0.002388998338733928 -1.5884512757453997]
 [0 0 0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  81432 489152 1347555 1689643 1925660 -0.4432074376818647
  -1.0471749418247094 -1.2291466102148794]
 [0 0 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  103206 443832 2099968 1973986 2403394 0.05252928385261084
  0.6081585447676027 -0.22249372431564235]
 [0 0 0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  205388 737610 1241882 2138864 2376254 -0.7612860344649259
  -0.19226109986142118 -0.5604427493064715]
 [0 0 0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 'Agustus'
  157586 600221 1402858 1661449 2149123 -0.6501675911810118
  1.3589125918261578 0.4632541702113187]
 [0 0 0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 59066 547164 1522465 1657452 2111256 -0.1847741205793414
  2.2441310241989045 1.1372386762962559]
 [0 0 0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 126972 601753 1418683 1736670 2043697 -1.2306473170526138
  -0.3640678995651204 -0.4991725456902981]]

In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 112435 523400 1421873 1821429 1874799 -1.7358732843053046
  -0.9337587771025072 -1.2852220328037356]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 55554 371542 1004961 1373919 2280029 0.5799132475106605
  -0.427865074822682 0.11647340415869879]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  'Agustus' 94301 438519 2179792 2264198 2532204 0.47697020491647923
  0.9298290479511115 -0.4170986853507955]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Agustus' 31379 428813 1410537 1621518 2662444 3.066066064169962
  0.07289241419488197 2.125798759325852]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  'Agustus' 15206 663125 1274153 1500807 2478173 0.8814472507725548
  -1.2859296247399525 0.2385170259563197]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  'Februari' 35761 346778 1006744 1251352 1748834 0.16550024862668541
  -0.2783276280836693 1.1672420632922837]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  'Februari' 92331 546897 1292234 1281240 1552894 -0.033218811931304694
  -0.44497957128277593 -0.16961980786168537]]